### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by sivaraam** [commons-app/commons-app-documentation#13]
By default when cloning the repo it uses the repo name as the folder name. As "documentation" is a common word it might not be the best name for the folder as it doesn't communicate much about what the repo is about.

How about renaming the repo to `commons-app-documentation`? I believe this shouldn't be an issue given that the repo is fairly new.

**Comment by domdomegg** [comment]
I kinda like having it just being `documentation`, given the organization name already identifies that it's part of the commons app. You can clone it to a custom folder name with `git clone git@github.com:commons-app/documentation.git commons-app-documentation`. Although I'm happy to change it if you reckon it'd be easier for new contributors, not attached to either way.

**Comment by sivaraam** [comment]
> I kinda like having it just being documentation, given the organization name already identifies that it's part of the commons app.

I understand the redundancy here. The point is that the organization name only appears on GitHub but only the repo name plays the main role outside of GitHub (e.g. in your local clone). So, I think it would be better if the repo name contains enough information about what the repo is about. Hence my suggestion.

> You can clone it to a custom folder name with git clone git@github.com:commons-app/documentation.git commons-app-documentation

I'm aware of that :) Just think about how many would even think of doing the "extra thing" of adding a custom folder name when cloning the repo.

**Comment by domdomegg** [comment]
That makes sense :)

I've renamed the repo, luckily GitHub redirects the old url to the new one so we're okay there. We can always switch back if others are unhappy (and they can do the git command the other way - `git clone git@github.com:commons-app/commons-app-documentation.git documentation`)
