### ISSUE TITLE
fix: add screenshot of new version of Android Studio in Readme

### ISSUE THREAD

**Issue by Bhavnaharitsa** [commons-app/commons-app-documentation#15]
https://github.com/commons-app/commons-app-documentation/blob/master/android/Getting-app-logs-from-Android-Studio.md
In this particular link, the Android Studio screenshot is of the older version, whereas the 3.6 Android Studio had a different UI. 
We need to change it :)

I am ready to take up the issue if mentors permit for it

**Comment by macgills** [comment]
Also these directions are outdated, logcat is right there in a tab in AS now.
Or you can use logcat directly
```
adb logcat > logcat.txt
```

Maybe we should just link to the [official docs](https://developer.android.com/studio/debug/am-logcat#running)

**Comment by Bhavnaharitsa** [comment]
@macgills Yes Ma'am, linking to the official docs will be more useful. But what about downloading Android Studio all such instructions? Should they be kept or can be removed? Please enlighten :)

**Comment by macgills** [comment]
I'd say keep the installing & enabling dev options. At 4 reference the docs, take out all images and maybe suggest the user copy and paste the logs? I don't know if there is any particular documentation philosophy at play here, maybe @misaochan or @domdomegg can weigh in

**Comment by misaochan** [comment]
> keep the installing & enabling dev options. At 4 reference the docs, take out all images and maybe suggest the user copy and paste the logs?

This sounds good to me, it reduces the burden on us to keep up to date with AS updates.

**Comment by domdomegg** [comment]
Agreed, happy for someone to make that change. Feel free to tag me for a review if necessary.

**Comment by Bhavnaharitsa** [comment]
> keep the installing & enabling dev options. At 4 reference the docs, take out all images and maybe suggest the user copy and paste the logs?
> 
> This sounds good to me, it reduces the burden on us to keep up to date with AS updates.

'yes, I can make the change but could you suggest me a good IDE to edit docs?

**Comment by macgills** [comment]
Well I use Android studio because I am using it already, there is markdown support for you to preview as you type
![image](https://user-images.githubusercontent.com/3358282/82643653-d1654300-9c07-11ea-95ee-14af66493b58.png)
but if you don't have AS already I do not recommend downloading it for markdown editing alone, seems like overkill.
From a quick google [this](https://pandao.github.io/editor.md/en.html) is open source?

**Comment by Bhavnaharitsa** [comment]
> Well I use Android studio because I am using it already, there is markdown support for you to preview as you type
> ![image](https://user-images.githubusercontent.com/3358282/82643653-d1654300-9c07-11ea-95ee-14af66493b58.png)
> but if you don't have AS already I do not recommend downloading it for markdown editing alone, seems like overkill.
> From a quick google [this](https://pandao.github.io/editor.md/en.html) is open source?

Okay thanks. I use Android Studio too. This seems good.
