### ISSUE TITLE
fix: Resize images in Volunteers.md file

### ISSUE THREAD

**Issue by Bhavnaharitsa** [commons-app/commons-app-documentation#16]
The image size is very big for the desktop window and also for the phone window. I think we need to Resize it to a compatible size. 

https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md
Please refer here

@domdomegg Your thoughts on this? :)

**Comment by misaochan** [comment]
Resizing sounds good to me.

**Comment by domdomegg** [comment]
Sounds good to me too.

I've opened #17, but also happy just to set the widths with something like `<img src="https://i.imgur.com/GyBqL6X.png" alt="Join beta program" width="400"/>`, although this does hardcode the size to 400 (rather than respond to the browser's width).
