### ISSUE TITLE
fix: Resize of images in Tutorial for new Images

### ISSUE THREAD

**Issue by Bhavnaharitsa** [commons-app/commons-app-documentation#19]
**Description**
https://github.com/commons-app/commons-app-documentation/blob/master/android/Tutorial-for-new-users.md

The images are quite big for both phone screen and desktop screen. They need to be resied as they were in Volunteers-Welcome.

I would like to work on the issue.

**Comment by maskaravivek** [comment]
Sure, you can pick this issue.
