### ISSUE TITLE
fix: Bold the other titles as well in Screen Structure

### ISSUE THREAD

**Issue by Bhavnaharitsa** [commons-app/commons-app-documentation#22]
https://github.com/commons-app/commons-app-documentation/blob/master/android/Screen-structure.md
The Screen Structure file has titles accordingly, but the titles "Log In", "My Recent Uploads", etc are in bold while the others are normal. I guess the other titles should be bolded as well. 
@domdomegg @misaochan @maskaravivek Please see if we need this so that I can work on it with your approval :)

**Comment by domdomegg** [comment]
Sure, feel free to work on this issue. I'd be happy for you to tag me for review.

Unless they're very large or time-consuming changes, for now feel free to submit PRs and tag me without raising an issue. We ask contributors to check before starting work on the main app so we avoid two people working on the same thing, and we can shape the strategic direction of the app before people put the effort in but I don't think that's necessary here as:
- There's less traffic on this repository, so you're unlikely to pick up an issue that someone is already working on but hasn't submitted a PR for
- Documentation changes are generally easier to do than changing app functionality, so if it ends up not being used there's not too much loss

If they are potentially contraversial changes, will take a lot of effort to do or you do want some more feedback before getting started do continue to create issues and ask for feedback though! :)

I dunno if other maintainers agree/disagree with this., would love to hear others ideas.

**Comment by Bhavnaharitsa** [comment]
@domdomegg Thank you for letting me know :). I shall follow accordingly and yeah, I sure shall tag you on further reviews :)

**Comment by misaochan** [comment]
I agree @domdomegg . :) Unlike the main repo, I think for this one it's okay to submit PRs without creating an issue first (unless perhaps the change is very controversial or time-consuming).

**Comment by Roshan13046** [comment]
I would like to fix this issue and send a PR.

**Comment by misaochan** [comment]
Thanks @Roshan13046 !
