### ISSUE TITLE
location upload fails

### ISSUE THREAD

**Issue by chelikol** [commons-app/commons-app-documentation#30]
I used the commons-app several years on a motorola smartphone. Now i got a new xiaomi smart phone mi 10. I installed the commons app, gave location rights to the app, the camera, the gallery app and google photos. But the upload begins with the question, weather the location is on earth and after the upload the location is missed in the commons. Is this a bug in the app or in xiaomi or is this a dau-issue?

**Comment by sivaraam** [comment]
Hi @chelikol! This repository is for the documentation of the Commons app. To file issues about the app itself, kindly [open an issue](https://github.com/commons-app/apps-android-commons/issues/new) in the app's repository. Thanks!
