### ISSUE TITLE
Spelling Mistake in Contributing-Guidelines.md file.

### ISSUE THREAD

**Issue by Roshan13046** [commons-app/commons-app-documentation#31]
In the "Describe your Changes Well" Paragraph there is a spelling mistake:
Current Spelling: "man"
Expected Spelling: "main"

Link: https://github.com/commons-app/commons-app-documentation/blob/master/android/Contributing-Guidelines.md#describe-your-changes-well

Image:
![Screenshot (697)_LI](https://user-images.githubusercontent.com/55108788/105579341-f66c1000-5dab-11eb-81d1-5696947c3884.jpg)

**Comment by domdomegg** [comment]
Hi, I believe this is correct and refers to the man page (https://en.wikipedia.org/wiki/Man_page)

**Comment by Roshan13046** [comment]
> Hi, I believe this is correct and refers to the man page (https://en.wikipedia.org/wiki/Man_page)

My fault. Should I close this issue?

**Comment by domdomegg** [comment]
Hi Roshan, yep I think we can close this for now. Thank you for your contribution, we certainly appreciate your enthusiasm to help improve the project's documentation and would welcome any future contributions!
