### ISSUE TITLE
Another app for word pronunciation

### ISSUE THREAD

**Issue by sivaraam** [commons-app/commons-app-documentation#38]
I happened to stumble across the [FAQ document](https://github.com/commons-app/commons-app-documentation/blob/master/android/Frequently-Asked-Questions.md) where I saw the following:

> How to contribute word pronunciation?
>
>>    Use this dedicated webapp (usable on mobile): https://lingualibre.fr/

I just wanted to note that there's also [Spell4Wiki ](https://github.com/manimaran96/Spell4Wiki)which could be for contributing word pronunciations.

I'm note really sure how the FAQ doc is used. Wanted to share the suggestion regardless 🙂 

cc @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Fixed, thanks! :-)
