### ISSUE TITLE
In Student steps, do not link to a Phabricator Maniphest overview page with no parameters

### ISSUE THREAD

**Issue by aklapper** [commons-app/commons-app-documentation#45]
https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md currently only states:

> Create a proposal on [Phabricator](https://phabricator.wikimedia.org/maniphest/) (button "Create Task").

This is unspecific and leads to tasks based on copy-and-paste, and to missing project tags on created tasks. Can you please change this to

> Create a proposal on Phabricator ([more info about Wikimedia Phabricator](https://www.mediawiki.org/wiki/Phabricator/Help)) by using the link under ["Submit your proposal as a task on Wikimedia Phabricator"](https://www.mediawiki.org/wiki/Google_Summer_of_Code/Participants).

or something like that? Thanks for considering.

**Comment by domdomegg** [comment]
Good idea. Done in https://github.com/commons-app/commons-app-documentation/commit/d19afffddd50319478ced5272b3ea5347df551f4
